server:
  port: 8080
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://database:5432/dev
    username: postgres
    password: postgres
  flyway:
    schemas: users
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: users