version: "3.8"

services:
  database:
    container_name: database
    image: postgres:15.5-alpine3.19
    ports:
      - 5432:5432
    env_file:
      - ./docker/environment/database.env
    networks:
      - developerNetwork

networks:
  developerNetwork:
    name: developerNetwork