version: "3.8"

services:
  database:
    container_name: database
    image: postgres:15.5-alpine3.19
    ports:
      - 5432:5432
    env_file:
      - ./docker/environment/database.env
    networks:
      - storeNetwork

  product:
    container_name: product
    image: silviocavalcanti/store-product-api:0.1.0
    ports:
      - 8081:8081
    env_file:
      - ./docker/environment/database.env
    networks:
      - storeNetwork
    depends_on:
      - database

  user:
    container_name: user
    image: silviocavalcanti/store-user-api:0.1.0
    ports:
      - 8080:8080
    env_file:
      - ./docker/environment/database.env
    networks:
      - storeNetwork
    depends_on:
      - database

  shopping:
    container_name: shopping
    image: silviocavalcanti/store-shopping-api:0.1.0
    ports:
      - 8082:8082
    env_file:
      - ./docker/environment/database.env
      - ./docker/environment/endpoint.env
    networks:
      - storeNetwork
    depends_on:
      - database

networks:
  storeNetwork:
    name: storeNetwork