apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoint-secret
  namespace: store
  labels:
    app: endpoint-secret
data:
  PRODUCT_API_URL: http://product-api.store.svc.cluster.local:8081
  USER_API_URL: http://user-api.store.svc.cluster.local:8080
immutable: true