GET http://localhost:8082/shopping HTTP/1.1

###
POST http://localhost:8082/shopping HTTP/1.1
Content-Type: application/json
key: 1519b941-de3e-4a3d-a699-a150598cb521

{
  "userIdentifier":"12345678910",
  "items":[
    {
      "productIdentifier":"tv",
      "amount": 2
    }
  ]
}

###
GET http://localhost:8082/shopping/shopByUser/1234567890 HTTP/1.1

###
GET http://localhost:8082/shopping/search?start=15/12/2000 HTTP/1.1

###
GET http://localhost:8082/shopping/search HTTP/1.1

###
GET http://localhost:8082/shopping/search?start=15/12/2023&end=17/12/2023&min=1000 HTTP/1.1

###
GET http://localhost:8082/shopping/report HTTP/1.1

###
GET http://localhost:8082/shopping/report?start=15/12/2023 HTTP/1.1
###
GET http://localhost:8082/shopping/report?start=15/12/2023&end=18/12/2023 HTTP/1.1