GET http://localhost:8082/shopping HTTP/1.1

###
POST http://localhost:8082/shopping HTTP/1.1
Content-Type: application/json
key: 10b462ae-652a-4ad6-bfe4-e8f97fd901a9

{
  "userIdentifier":"12345678910",
  "total": 200,
  "date": "2019-11-17T21:04:19.828+0000",
  "itens":[
    {
      "productIdentifier":"video-game",
      "price": 2001.0
    }
  ]
}

###
GET http://localhost:8082/shopping/shopByUser/1234567890 HTTP/1.1

###
GET http://localhost:8082/shopping/search?start=15/12/2000 HTTP/1.1

###
GET http://localhost:8082/shopping/search HTTP/1.1

###
GET http://localhost:8082/shopping/search?start=15/12/2023&end=17/12/2023&min=1000 HTTP/1.1

###
GET http://localhost:8082/shopping/report HTTP/1.1

###
GET http://localhost:8082/shopping/report?start=15/12/2023 HTTP/1.1
###
GET http://localhost:8082/shopping/report?start=15/12/2023&end=18/12/2023 HTTP/1.1