GET http://localhost:8081/product HTTP/1.1

###
GET http://localhost:8081/product/category/1 HTTP/1.1

###
POST http://localhost:8081/product HTTP/1.1
Content-Type: application/json

{
  "productIdentifier":"tv",
  "name":"TV",
  "price": 1000,
  "description": "Uma TV",
  "category":{
    "id": 1
  } 
}
###
POST http://localhost:8081/product HTTP/1.1
Content-Type: application/json

{
  "productIdentifier":"video-game",
  "name": "Video Game",
  "price": 2000.0,
  "description": "Um video game",
  "category":{
    "id": 5
  }
}

###
GET http://localhost:8081/product/tv HTTP/1.1

###
DELETE http://localhost:8081/product/tv HTTP/1.1