server:
  port: 8081
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${POSTGRES_URL:jdbc:postgresql://database:5432/dev}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    schemas: products
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: products